synapse:
  dataset:
    id: syn22296821
    name: Data files for derived variables
    type: table
    description: Links derived variable Synapse entities to dataset names.
check:
  1: 
    function: check_code_name_empty
    implemented: 1
    deprecated: 0
    description: Code is empty.
    request: Please remove the row or fill in the code name. 
  2: 
    function: check_code_name_absent
    implemented: 1
    deprecated: 0
    description: Code does not exist in associated dataset.
    request: Please check the code name and associated dataset. 
  3:
    function: check_dataset_names
    implemented: 1
    deprecated: 0
    description: Dataset name does not exist.
    request: Please check dataset name is associated with a dataset.  