synapse:
  dataset:
    id: syn22296821
    name: Data files for derived variables
    type: table
    description: Links derived variable Synapse entities to dataset names.
column_name:
  sor_cbio:
    BLADDER:
      1.1-consortium: Cbio_Bladder_V1
    BRCA:
      1.1-consortium: Cbio_BrCa_V1
    CRC:
      1.1-consortium: Cbio_CRC_V1
      1.2-consortium: Cbio_CRC_V1.2
    NSCLC:
      1.1-consortium: Cbio_NSCLC_V2.1
      2.1-consortium: Cbio_NSCLC_V2.1
      2.0-public: Shared for NSCLC Public Release
    PANC:
      1.1-consortium: Cbio_PANC_V1
    PROSTATE:
      1.1-consortium: Cbio_Prostate_V1
check:
  1: 
    function: check_code_name_empty
    implemented: 1
    deprecated: 0
    description: Code is empty.
    request: Please remove the row or fill in the code name. 
  2: 
    function: check_code_name_absent
    implemented: 1
    deprecated: 0
    description: Code does not exist in associated dataset.
    request: Please check the code name and associated dataset. 
  3:
    function: check_dataset_names
    implemented: 1
    deprecated: 0
    description: Dataset name does not exist.
    request: Please check dataset name is associated with a dataset.  
  4:
    function: check_release_status_ambiguous
    implemented: 1
    deprecated: 0
    description: Release status in mapping file is ambiguous.
    request: Please update release status in mapping file.  