dataset:
  'Cancer-level dataset':
    id: syn22296816  
    file: ca_dx_derived.csv
  'Patient-level dataset':
    id: syn22296817
    file: pt_derived.csv
  'Regimen-Cancer level dataset':
    id: syn22296818
    file: ca_drugs_derived.csv
  'Imaging-level dataset':
    id: syn22296819
    file: prissmm_image_derived.csv
  'Pathology-report level dataset':
    id: syn22296820
    file: prissmm_path_derived.csv
  'Med Onc Note level dataset':
    id: syn22296822
    file: prissmm_md_derived.csv
  'Cancer panel test level dataset':
    id: syn22296823
    file: cpt_derived.csv
  'Cancer-level index dataset': 
    id: syn22314486
    file: ca_dx_derived_index.csv
  'Cancer-level non-index dataset': 
    id: syn22314497
    file: ca_dx_derived_non_index.csv
  'Hemeonc dataset':
    id: syn23561688
    file: hemonc_mapping_cbio.csv
  'PRISSMM Tumor Marker level dataset':
    id: syn23561700
    file: prissmm_tm_derived.csv
  'Cancer-Directed Radiation Therapy dataset':
    id: syn25931923  
    file: ca_radtx_derived.csv
check:
  1: 
    function: check_code_name_empty
    implemented: 1
    deprecated: 0
    description: Code is empty.
    request: Please remove the row or fill in the code name. 
  2: 
    function: check_code_name_absent
    implemented: 1
    deprecated: 0
    description: Code does not exist in associated dataset.
    request: Please check the code name and associated dataset. 