synapse:
  dataset:
    id: syn22296821
    name: Data files for derived variables
    type: table
    description: Links derived variable Synapse entities to dataset names.
  catalog:
    id: syn21431364
    name: GENIE BPC No PHI Data Elements Catalog
    type: table
    description: cumulative data catalog reference of all BPC curated and derived data elements
  sor: 
    id: syn22294851
    name: GENIE_BPC_Release_Scope.xlsx
    type: file
    description: stats team Scope of Release for GENIE BPC
    column_name:
      BLADDER:
        1.1-consortium: Cbio_Bladder_V1_1_Pharma
      BRCA:
        1.1-consortium: Cbio_BrCa_V1
        2.0-public: Cbio Breast Public Release
      CRC:
        1.1-consortium: Cbio_CRC_V1
        1.2-consortium: Cbio_CRC_V1.2
        2.0-public: Cbio CRC Public Release
      NSCLC:
        1.1-consortium: Cbio_NSCLC_V2.1
        2.1-consortium: Cbio_NSCLC_V2.1
        2.0-public: Shared for cBio NSCLC 2.0-Public Release
      PANC:
        1.1-consortium: Cbio_PANC_V1
      PROSTATE:
        1.1-consortium: Cbio_Prostate_V1_1_Pharma
check:
  1: 
    function: check_code_name_empty
    implemented: 1
    deprecated: 0
    description: Code is empty.
    request: Please remove the row or fill in the code name. 
  2: 
    function: check_code_name_absent
    implemented: 1
    deprecated: 0
    description: Code does not exist in associated dataset.
    request: Please check the code name and associated dataset. 
  3:
    function: check_dataset_names
    implemented: 1
    deprecated: 0
    description: Dataset name does not exist.
    request: Please check dataset name is associated with a dataset.  
  4:
    function: check_release_status_ambiguous
    implemented: 1
    deprecated: 0
    description: Release status in mapping file is ambiguous.
    request: Please update release status in mapping file.  
  5:
    function: check_release_status_map_yes_sor_not
    implemented: 1
    deprecated: 0
    description: Released in mapping file but not scope of release.
    request: Please double check release status in mapping file.  
  6:
    function: check_release_status_sor_yes_map_not
    implemented: 1
    deprecated: 0
    description: Released in scope of release but not mapping file.
    request: Please double check release status in mapping file.  
  7: 
    function: check_code_name_catalog
    implemented: 1
    deprecated: 0
    description: Code does not exist in data element catalog.
    request: Please notify Sage that this variable needs to be added to the catalog. 